Added Principal Component Analysis
Math-behind-AI/ScratchAI pull request #31
Opened 2022-10-27 04:53 UTC by pps-19012

Added PCA and implementation of PCA in Face Recognition

## Changes: 
1. PCA .ipynb file + dataset
2. Face Recognition folder - 1 pdf + 1 .ipynb + dataset

## Type of change

- [ ] Documentation update
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New layer/algorithm

### Implementation details

> * List all the packages and their versions used.
Mentioned in README.

## Tests

Run the i.pynb files. It has README instructions to run successfully.

## Checklist

- [ ] I have performed a self code_review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.

2022-10-27 12:14 UTC, HemanthSai7 reviewed
@pps-19012 you previously made a PR on PCA. Why again?

2022-10-27 12:24 UTC, mayureshagashe2105 requested changes
Please resolve the merge conflicts and please explain why have you opened this PR again.

2022-10-27 12:24 UTC, mayureshagashe2105 commented on README.md
> +      * [Principal Component Analysis](traditional_ML_algorithms/Principal%20Component%20Analysis)
Resolve the merge conflict first.

2022-10-27 12:24 UTC, mayureshagashe2105 commented on traditional_ML_algorithms/Principal Component Analysis/PCA_FaceRecognition/readme.md
> +Face Recognition is an important implementation of PCA. It uses eigenvectors of the covariance vectors of the image matrix to detect and recognize faces.
Resolve the merge conflict first!

2022-10-27 12:24 UTC, mayureshagashe2105 commented on traditional_ML_algorithms/Principal Component Analysis/README.md
> +
Resolve the merge conflict first!

2022-10-27 12:39 UTC, pps-19012 commented
The previous PR had implementation of algorithm only on a specific topic (Face Recognition). Now, it also has general implementation.

2022-10-27 12:44 UTC, mayureshagashe2105 commented
Alright, sounds good! Please resolve the merge conflicts.

2022-10-28 03:51 UTC, pps-19012 commented
Done!

2022-10-28 05:05 UTC, HemanthSai7 approved these changes
LGTM🚀. Merging

2022-10-28 05:06 UTC, mayureshagashe2105 commented
LGTM!

2022-10-28 05:07 UTC, mayureshagashe2105 approved these changes

2022-10-28 05:07 UTC, merged